// ClientApp.Angular/src/app/contact-manager/company-edit.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';

import {CompanyHttpService, ICompanyDto} from '@services/contact-manager/company-http.service';

@Component({
  templateUrl: './company-edit.component.html'
})

export class CompanyEditComponent implements OnInit {

  private _company: ICompanyDto;

  constructor(private activatedRoute: ActivatedRoute, private companyHttpService: CompanyHttpService) {
  }

  public get company(): ICompanyDto {
    return this._company;
  }

  /**
   * OnInit
   */
  public ngOnInit(): void {
    this.activatedRoute.params
      .subscribe(params => {
        this.loadCompany(params.companyId);
      });
  }

  public async handleUpdateClick(): Promise<void> {

    await this.companyHttpService.updateCompany(this._company);
  }

  private async loadCompany(companyId: number): Promise<void> {

    this._company = await this.companyHttpService.getCompany(companyId);
  }
}

<div *ngIf="company">
  <div>
    Name:
    <input type="text" [(ngModel)]="company.name">
  </div>
  <div>
    Description:
    <input type="text" [(ngModel)]="company.description">
  </div>
  <div>
    <button (click)="handleUpdateClick()">Update</button>
  </div>
</div>

// ClientApp.React/src/app/contact-manager/company-edit.component.tsx
import * as React from 'react';
import {RouteComponentProps} from 'react-router-dom';
import {Button, TextField} from '@core/mui-exports';

import {ICompanyDto} from '@http-services/contact-manager/company-http.service';
import {ICompaniesContext, CompaniesContextTypes, TCompaniesContextTypes} from './companies-context';

interface IRouteParams {
  companyId: string;
}

interface IProps extends RouteComponentProps<IRouteParams>, React.HTMLProps<any> {
}

interface IState {
  company?: ICompanyDto;
}

/**
 * Edit mode for companiies
 */
export class CompanyEditComponent extends React.Component<IProps, IState> {

  private _companiesContext: ICompaniesContext;
  public static contextTypes: TCompaniesContextTypes = CompaniesContextTypes;

  constructor(props: IProps, context: ICompaniesContext) {
    super(props);

    this.state = {};
    this._companiesContext = context;
  }


  /**
   * React.Component
   */
  public render(): React.ReactNode {
    return (
      <div style={this.props.style}>{this.state.company &&
        <div>
          <div>
            <TextField fullWidth={true} value={this.state.company.name} onChange={(e) => {this.handleCompanyNameChange(e)}} />
          </div>
          <div>
            <TextField fullWidth={true} value={this.state.company.description} onChange={(e) => {this.handleCompanyDescriptionChange(e)}} />
          </div>

          <div style={{display: 'flex', flexDirection: 'row', justifyContent: 'flex-end'}}>
            <Button variant="raised" color="primary" onClick={() => {this.handleUpdateClick();}}>Update</Button>
          </div>
        </div>
      }
      </div>
    );
  }

  /**
   * ComponentLifecycle
   */
  public componentDidMount(): void {
    this.loadCompany();
  }

  private async loadCompany(): Promise<void> {

    let companyId = Number.parseInt(this.props.match.params.companyId);
    let company = await this._companiesContext.companyHttpService.getCompany(companyId);
    this.setState({company: company});
  }


  /**
   * Invoked when user clicks Update button
   */
  private async handleUpdateClick(): Promise<void> {
    if(this.state.company) {
      this._companiesContext.companyHttpService.updateCompany(this.state.company);
    }
  }

  /**
   * Invoked when user changes company name
   */
  private handleCompanyNameChange(event: React.ChangeEvent<HTMLInputElement>): void {

    event.persist();
    this.setState(prevState => {
      return {...prevState, company: {...prevState.company, name: event.target.value} as ICompanyDto};
    });
  }

  /**
   * Invoked when user changes company description
   */
  private handleCompanyDescriptionChange(event: React.ChangeEvent<HTMLInputElement>): void {

    event.persist();
    this.setState(prevState => {
      return {...prevState, company: {...prevState.company, description: event.target.value} as ICompanyDto};
    });
  }
}
